# Example config file to use as a starting point.
# Please visit https://docs.beetleboxci.com/docs/config/configuration-yaml for guidance on setting up your configuration file.

# Define a runner that will be used to run a job
runners:
 ubuntu-runner:
  image: public.ecr.aws/y2s4f3y9/ubuntu-generic:latest

# Define a job to be performed during a workflow
jobs:   
 avr-compile-program-close:
  # Specify the runner used to perform this job
  runner: ubuntu-runner
  privileged: True
  device: AVR-microcontroller-1
  volumes:
   - mount:
      name: volume1
      path: <your_mplabx_installation_directory>
  steps:
    - run:
        name: Setup Environment
        command: |
          apt-get -y update
          apt-get install make
          apt-get install libusb-1.0-0
          apt-get install python3.10  -y
          apt-get -y install python3-pip 
          pip3 install pySerial 
    - run:
        name: Compile AVR chip
        command: |
          export PATH=$PATH:<your_mplabx_installation_directory>/mplabx/<your_mplabx_version_number>/mplab_platform/bin
          make
    - run:
        name: Program AVR board
        command: |
          python3 ./MonitorOutput.py > AVROutput.txt &
          mdb='<your_mplabx_installation_directory>/mplabx/<your_mplabx_version_number>/mplab_platform/bin/mdb.sh'
          $mdb mdb-avr-example.txt
          wait $(jobs -p)
    - run:
        name: Parse Output Files
        command: |
          cat AVROutput.txt
          python3 ./ParseOutput.py AVROutput.txt

# Define a workflow to orchestrate a job
workflows:
 avr-workflow:
  jobs:
   - avr-compile-program-close
